version: '3'
services:
  app:
    container_name: appNode
    build: .
    command: yarn dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3333:3333"
    env_file: .env
    depends_on:
      - db
      - mongo
      - redis
  db:
    container_name: postgres_dev
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: engajei
  redis:
    container_name: redis_dev
    image: redis:alpine
    ports:
      - "6379:6379"
  mongo:
    container_name: mongoDB_dev
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

